### ISSUE TITLE
Сломаные миграции

### ISSUE THREAD

**Issue by AlonsoMackenlly** [IMZolin/Todolist-Telegram-bot#1]
Привет! Попробовал запустить твой проект, заметил на старте проекта что есть не некорректные миграции.

**Comment by AlonsoMackenlly** [comment]
[
![image](https://github.com/IMZolin/Todolist-Telegram-bot/assets/19227850/04ce26bc-6a8b-4d82-9dde-35dd0ff0ab5c)
](url)

**Comment by AlonsoMackenlly** [comment]
Выполнил внутри контейнера `pw_migrate merge` и с одной миграцией поднялся проект.

**Comment by IMZolin** [comment]
Верно и я понимаю, что вопрос исчерпал сам себя(нашли сами ответ) и этот issue я могу закрыть?

**Comment by IMZolin** [comment]
Если есть какие-то ещё вопросы, можете их задавать, возможно открыв другой issue.

**Comment by IMZolin** [comment]
Также я пока что не доделал до конца верную сборку Docker, поэтому, если проблемы именно там (как я понял из сообщения выше про контейнер), то это "нормально". Позже этим займусь, но всё равно спасибо!

**Comment by AlonsoMackenlly** [comment]
Да, можно закрыть, а про Docker в .env.example файлике я бы на твоём месте явно указал POSTGRES_HOST и т.д. по дефолту и их же прокинуть надо в docker-compose.yml, т.к. энвы прописываются а в конфиге компоуза не участвуют, при старте с нуля джанга кричит что не могу соединиться.
